FROM golang:1.13

  # create project directory
RUN mkdir -p src/github.com/toorosan/grpc-csv-viewer

  # copy project files and folders to the current working directory
COPY . src/github.com/toorosan/grpc-csv-viewer

  # run application
CMD cd src/github.com/toorosan/grpc-csv-viewer && go run cmd/server/main.go -listen_addr ":8082" -csv_files_path misc/csv_files -log_level debug