version: '3'
services:
  client:
    build:
      context: ..
      dockerfile: ./misc/Dockerfile-client
    depends_on:
      - server
    links:
      - server:server
    ports:
      - "8081:8081"
    volumes:
      - ../:./src/github.com/toorosan/grpc-csv-viewer
  server:
    build:
      context: ..
      dockerfile: ./misc/Dockerfile-server
    ports:
      - "8082:8082"
    volumes:
      - ../:./src/github.com/toorosan/grpc-csv-viewer
  ui:
    build:
      context: ../internal/app/roles/client/ui
      dockerfile: ../../../../../misc/Dockerfile-ui
    ports:
      - "8080:8080"
    volumes:
      - ../internal/app/roles/client/ui:/
  proxy:
    image: nginx:alpine
    links:
      - client:client
      - ui:ui
    ports:
      - "8888:80"
    volumes:
      - ./nginx-all-containers.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - ui