version: '3'
services:
  dockerhost:
    image: alpine
    entrypoint: /bin/sh -c "tail -f /dev/null"
    network_mode: host
  proxy:
    image: nginx:alpine
    links:
      - dockerhost:dockerhost
    ports:
      - "8888:80"
    volumes:
      - ./nginx-dev-default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - dockerhost