#%RAML 1.0
title: gRPC Client API
version: v1
baseUri: http://localhost/api/{version}/
mediaType: application/json

traits:
  errorInternal:
    description: Internal error occurred.
    responses:
      500:
  errorBadGateway:
    description: Bad Gateway error occurred.
    responses:
      502:
        body:
          schema:
            type: object
            properties:
              message: string

types:
  FileDetails:
    type: object
    properties:
      fileName:
        description: Name of the CSV file.
        type: string
      startDate:
        description: Unix timestamp of the earliest date available in the original values list.
        type: number
      stopDate: Unix timestamp of the latest date available in the original values list.
        description:
        type: number
  SeriesItem:
    type: object
    properties:
      date: datetime
      value:
        type: number
        format: float
  TimeSeries:
    type: FileDetails
    properties:
      values:
        type: array
        items: SeriesItem

/timeseries:
  is: [ errorInternal, errorBadGateway ]
  get:
    description: Get time series.
    responses:
      200:
        body:
          schema: TimeSeries

/files:
  is: [ errorInternal, errorBadGateway ]
  get:
    description: Get list of available CSV files.
    responses:
      200:
        body:
          type: array
          items: FileDetails